-- DROP DATABASE
<<<<<<< HEAD
DROP DATABASE IF EXISTS jogjotter_db;

-- CREATE DATABASE
CREATE DATABASE jogjotter_db;
=======
DROP DATABASE IF EXISTS JogJotter_db;

-- CREATE DATABASE
CREATE DATABASE JogJotter_db;
>>>>>>> 5092aae4a2a88b2005c505c3c5c4584bc1d2d8a7
